# Generated by Django 5.0.7 on 2024-07-10 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jugador', models.CharField(max_length=255)),
                ('combinacion', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Casilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado', models.BooleanField(default=False)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.carton')),
                ('musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.musical')),
            ],
        ),
        migrations.AddField(
            model_name='carton',
            name='musicales',
            field=models.ManyToManyField(through='bingo.Casilla', to='bingo.musical'),
        ),
    ]
