# Generated by Django 5.0.3 on 2024-08-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musical',
            name='elegido',
            field=models.BooleanField(default=False),
        ),
    ]
